// Helper functions used in other files

class Misc {
    constructor() {
        this.commands = [

        ];
    }

    sleep = (seconds) => 
        new Promise(resolve => setTimeout(resolve, seconds*1000))

    // Function to deverify members when they leave the server or when !d is used
    deverifyFunc = async(mid) => {
        const mongoose = require('mongoose')
        const {verified} = require('./models')

        mongoose.connect('mongodb://localhost:27017/pesu',
        {
            useNewUrlParser: true,
            useUnifiedTopology: true
        });

        const ret = await verified.findOneAndDelete({ID: mid})
        if(ret === null) {
            return false
        }
        else {
            return true
        }
    }

    // Test to check if message was regenerated by NQN
    // Returns false if no NQN message was regenerated
    nqnTest = async(message) => {
        let ret = false;
        const config = require("../../config.json")

        // Get NQN Audit Logs channel
        const nqnLogs = message.guild.channels.cache.get(config.nqnlogs)
        const lastMessage = nqnLogs.lastMessage // Latest message in the logs
        const author = lastMessage.author.username // NQN logs have username like this: `NQN on behalf of han (723377619420184668)`
        const openBracket = author.indexOf("(")
        const authorId = author.substring(openBracket+1, author.length-1) // Get the author ID, the number inside the brackets

        // User messages and NQN replaced messages have different message content
        // User message may look like `:sadsmile: no`
        // NQN replaced message will look like `<a:sadsmile:47856286545764578> no`
        // So it is necessary to clean out special characters, numbers and any other characters necessary for message content comparison
        const cleanedCont = message.content.replaceAll("<:", "").replaceAll("<a:", "").replaceAll(">", "").replaceAll(" ", "").replaceAll(/\d+/g, "").replaceAll(":", "").trim().toLowerCase()
        const cleanedLast = lastMessage.content.replaceAll("<:", "").replaceAll("<a:", "").replaceAll(">", "").replaceAll(" ", "").replaceAll(/\d+/g, "").replaceAll(":", "").trim().toLowerCase()
        
        if(cleanedCont === cleanedLast && message.author.id === authorId){
            ret = true;
            // A buffer message is sent to the logs channel so that the last message for the next deleted message in case it's not
            // nqn generated does not refer to an older deleted message
            await nqnLogs.send("buffer");
        }
        return ret;

    }

    // Function to run shell scripts in a promisified way
    shell = (cmd) => {   
        const { exec } = require('child_process')
        return new Promise((resolve, reject) => {
            cmd = cmd.replace(/\n/g, " && ")
            exec(
                cmd,
                (error, stdout, stderr) => {
                    if(error) throw error
                    resolve(stdout? stdout : stderr)
                })  
        })

    }

    
}
const misc = new Misc()

module.exports = misc